//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PISIEntities : DbContext
    {
        public PISIEntities()
            : base("name=PISIEntities")
        {
            var ensureDLLIsCopied = System.Data.Entity.SqlServer.SqlProviderServices.Instance;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_ACTIVIDAD> TB_ACTIVIDAD { get; set; }
        public virtual DbSet<TB_BENEFICIARIO> TB_BENEFICIARIO { get; set; }
        public virtual DbSet<TB_DOCUMENTO> TB_DOCUMENTO { get; set; }
        public virtual DbSet<TB_EJECUCION> TB_EJECUCION { get; set; }
        public virtual DbSet<TB_NOTIFICACION> TB_NOTIFICACION { get; set; }
        public virtual DbSet<TB_PERMISO> TB_PERMISO { get; set; }
        public virtual DbSet<TB_PERSONA> TB_PERSONA { get; set; }
        public virtual DbSet<TB_PROBLEMA> TB_PROBLEMA { get; set; }
        public virtual DbSet<TB_PROPUESTA> TB_PROPUESTA { get; set; }
        public virtual DbSet<TB_PROYECTO> TB_PROYECTO { get; set; }
        public virtual DbSet<TB_PROYECTO_ACTIVIDAD> TB_PROYECTO_ACTIVIDAD { get; set; }
        public virtual DbSet<TB_RECURSO> TB_RECURSO { get; set; }
        public virtual DbSet<TB_ROL> TB_ROL { get; set; }
        public virtual DbSet<TB_SOLICITUD_SEGUIMIENTO> TB_SOLICITUD_SEGUIMIENTO { get; set; }
        public virtual DbSet<TB_USUARIO> TB_USUARIO { get; set; }
        public virtual DbSet<TBC_ACTIVIDAD_INICIATIVA> TBC_ACTIVIDAD_INICIATIVA { get; set; }
        public virtual DbSet<TBC_DEPARTAMENTO> TBC_DEPARTAMENTO { get; set; }
        public virtual DbSet<TBC_ESTADO_PROCESO> TBC_ESTADO_PROCESO { get; set; }
        public virtual DbSet<TBC_MUNICIPIO> TBC_MUNICIPIO { get; set; }
        public virtual DbSet<TBC_PROCESO> TBC_PROCESO { get; set; }
        public virtual DbSet<TBC_SECTOR_ECONOMICO> TBC_SECTOR_ECONOMICO { get; set; }
        public virtual DbSet<TBC_TIPO_DOCUMENTO> TBC_TIPO_DOCUMENTO { get; set; }
        public virtual DbSet<TBC_TIPO_INICIATIVA> TBC_TIPO_INICIATIVA { get; set; }
        public virtual DbSet<TBC_TIPO_NOTIFICACION> TBC_TIPO_NOTIFICACION { get; set; }
    
        public virtual ObjectResult<Nullable<int>> SP_Autenticar(string cORREO_E, string cONTRASENA)
        {
            var cORREO_EParameter = cORREO_E != null ?
                new ObjectParameter("CORREO_E", cORREO_E) :
                new ObjectParameter("CORREO_E", typeof(string));
    
            var cONTRASENAParameter = cONTRASENA != null ?
                new ObjectParameter("CONTRASENA", cONTRASENA) :
                new ObjectParameter("CONTRASENA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Autenticar", cORREO_EParameter, cONTRASENAParameter);
        }
    
        public virtual ObjectResult<SP_DETALLE_USUARIO_Result> SP_DETALLE_USUARIO(Nullable<int> iD_USUARIO)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DETALLE_USUARIO_Result>("SP_DETALLE_USUARIO", iD_USUARIOParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_ROL_HAS_RECURSO(Nullable<int> iD_ROL, Nullable<int> iD_RECURSO)
        {
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(int));
    
            var iD_RECURSOParameter = iD_RECURSO.HasValue ?
                new ObjectParameter("ID_RECURSO", iD_RECURSO) :
                new ObjectParameter("ID_RECURSO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_ROL_HAS_RECURSO", iD_ROLParameter, iD_RECURSOParameter);
        }
    
        public virtual int SP_TB_ACTIVIDAD_InsertCita(Nullable<int> idUsuario, Nullable<System.DateTime> fecha, Nullable<System.DateTime> hora, string direccion, string descripcion, Nullable<int> uSUARIO_CREA)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var horaParameter = hora.HasValue ?
                new ObjectParameter("Hora", hora) :
                new ObjectParameter("Hora", typeof(System.DateTime));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var uSUARIO_CREAParameter = uSUARIO_CREA.HasValue ?
                new ObjectParameter("USUARIO_CREA", uSUARIO_CREA) :
                new ObjectParameter("USUARIO_CREA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_ACTIVIDAD_InsertCita", idUsuarioParameter, fechaParameter, horaParameter, direccionParameter, descripcionParameter, uSUARIO_CREAParameter);
        }
    
        public virtual int SP_TB_BENEFICIARIO_CambiarCodigo(string codBene, Nullable<int> idBeneficiario, Nullable<int> uSUARIO_ACTUALIZA)
        {
            var codBeneParameter = codBene != null ?
                new ObjectParameter("CodBene", codBene) :
                new ObjectParameter("CodBene", typeof(string));
    
            var idBeneficiarioParameter = idBeneficiario.HasValue ?
                new ObjectParameter("IdBeneficiario", idBeneficiario) :
                new ObjectParameter("IdBeneficiario", typeof(int));
    
            var uSUARIO_ACTUALIZAParameter = uSUARIO_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ACTUALIZA", uSUARIO_ACTUALIZA) :
                new ObjectParameter("USUARIO_ACTUALIZA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_BENEFICIARIO_CambiarCodigo", codBeneParameter, idBeneficiarioParameter, uSUARIO_ACTUALIZAParameter);
        }
    
        public virtual int SP_TB_BENEFICIARIO_CambiarEstado(string codProceso, Nullable<int> idBeneficiario, Nullable<int> uSUARIO_ACTUALIZA)
        {
            var codProcesoParameter = codProceso != null ?
                new ObjectParameter("CodProceso", codProceso) :
                new ObjectParameter("CodProceso", typeof(string));
    
            var idBeneficiarioParameter = idBeneficiario.HasValue ?
                new ObjectParameter("IdBeneficiario", idBeneficiario) :
                new ObjectParameter("IdBeneficiario", typeof(int));
    
            var uSUARIO_ACTUALIZAParameter = uSUARIO_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ACTUALIZA", uSUARIO_ACTUALIZA) :
                new ObjectParameter("USUARIO_ACTUALIZA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_BENEFICIARIO_CambiarEstado", codProcesoParameter, idBeneficiarioParameter, uSUARIO_ACTUALIZAParameter);
        }
    
        public virtual ObjectResult<SP_TB_BENEFICIARIO_GetById_Result> SP_TB_BENEFICIARIO_GetById(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_BENEFICIARIO_GetById_Result>("SP_TB_BENEFICIARIO_GetById", iDParameter);
        }
    
        public virtual ObjectResult<SP_TB_BENEFICIARIO_GetByIdPersona_Result> SP_TB_BENEFICIARIO_GetByIdPersona(Nullable<int> iD_PERSONA)
        {
            var iD_PERSONAParameter = iD_PERSONA.HasValue ?
                new ObjectParameter("ID_PERSONA", iD_PERSONA) :
                new ObjectParameter("ID_PERSONA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_BENEFICIARIO_GetByIdPersona_Result>("SP_TB_BENEFICIARIO_GetByIdPersona", iD_PERSONAParameter);
        }
    
        public virtual int SP_TB_BENEFICIARIO_InsertBeneficiario(Nullable<int> idSector, Nullable<int> idPersona, string cODIGO_BENEFICIARIO, Nullable<short> tipoPersona, string dui, string nit, Nullable<int> uSUARIO_CREA)
        {
            var idSectorParameter = idSector.HasValue ?
                new ObjectParameter("IdSector", idSector) :
                new ObjectParameter("IdSector", typeof(int));
    
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("IdPersona", idPersona) :
                new ObjectParameter("IdPersona", typeof(int));
    
            var cODIGO_BENEFICIARIOParameter = cODIGO_BENEFICIARIO != null ?
                new ObjectParameter("CODIGO_BENEFICIARIO", cODIGO_BENEFICIARIO) :
                new ObjectParameter("CODIGO_BENEFICIARIO", typeof(string));
    
            var tipoPersonaParameter = tipoPersona.HasValue ?
                new ObjectParameter("TipoPersona", tipoPersona) :
                new ObjectParameter("TipoPersona", typeof(short));
    
            var duiParameter = dui != null ?
                new ObjectParameter("Dui", dui) :
                new ObjectParameter("Dui", typeof(string));
    
            var nitParameter = nit != null ?
                new ObjectParameter("Nit", nit) :
                new ObjectParameter("Nit", typeof(string));
    
            var uSUARIO_CREAParameter = uSUARIO_CREA.HasValue ?
                new ObjectParameter("USUARIO_CREA", uSUARIO_CREA) :
                new ObjectParameter("USUARIO_CREA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_BENEFICIARIO_InsertBeneficiario", idSectorParameter, idPersonaParameter, cODIGO_BENEFICIARIOParameter, tipoPersonaParameter, duiParameter, nitParameter, uSUARIO_CREAParameter);
        }
    
        public virtual ObjectResult<SP_TB_BENEFICIARIO_ObterPorEstadoProceso_Result> SP_TB_BENEFICIARIO_ObterPorEstadoProceso(string codEstadoProceso)
        {
            var codEstadoProcesoParameter = codEstadoProceso != null ?
                new ObjectParameter("CodEstadoProceso", codEstadoProceso) :
                new ObjectParameter("CodEstadoProceso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_BENEFICIARIO_ObterPorEstadoProceso_Result>("SP_TB_BENEFICIARIO_ObterPorEstadoProceso", codEstadoProcesoParameter);
        }
    
        public virtual ObjectResult<SP_TB_NOTIFICACION_GetAll_Result> SP_TB_NOTIFICACION_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_NOTIFICACION_GetAll_Result>("SP_TB_NOTIFICACION_GetAll");
        }
    
        public virtual ObjectResult<SP_TB_NOTIFICACION_GetAllNoLeidas_Result> SP_TB_NOTIFICACION_GetAllNoLeidas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_NOTIFICACION_GetAllNoLeidas_Result>("SP_TB_NOTIFICACION_GetAllNoLeidas");
        }
    
        public virtual ObjectResult<SP_TB_NOTIFICACION_GetByIdUsuario_Result> SP_TB_NOTIFICACION_GetByIdUsuario(Nullable<int> iD_USUARIO)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_NOTIFICACION_GetByIdUsuario_Result>("SP_TB_NOTIFICACION_GetByIdUsuario", iD_USUARIOParameter);
        }
    
        public virtual ObjectResult<SP_TB_NOTIFICACION_GetLeidasByIdUsuario_Result> SP_TB_NOTIFICACION_GetLeidasByIdUsuario(Nullable<int> iD_USUARIO)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_NOTIFICACION_GetLeidasByIdUsuario_Result>("SP_TB_NOTIFICACION_GetLeidasByIdUsuario", iD_USUARIOParameter);
        }
    
        public virtual int SP_TB_NOTIFICACION_INSERT(Nullable<int> iD_USUARIO, Nullable<int> iD_TIPO_NOTIFICACION, string dESCRIPCION)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            var iD_TIPO_NOTIFICACIONParameter = iD_TIPO_NOTIFICACION.HasValue ?
                new ObjectParameter("ID_TIPO_NOTIFICACION", iD_TIPO_NOTIFICACION) :
                new ObjectParameter("ID_TIPO_NOTIFICACION", typeof(int));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_NOTIFICACION_INSERT", iD_USUARIOParameter, iD_TIPO_NOTIFICACIONParameter, dESCRIPCIONParameter);
        }
    
        public virtual int SP_TB_NOTIFICACION_UPDATE_LEIDO(Nullable<int> iD_NOTIFICACION, Nullable<short> eSTADO)
        {
            var iD_NOTIFICACIONParameter = iD_NOTIFICACION.HasValue ?
                new ObjectParameter("ID_NOTIFICACION", iD_NOTIFICACION) :
                new ObjectParameter("ID_NOTIFICACION", typeof(int));
    
            var eSTADOParameter = eSTADO.HasValue ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_NOTIFICACION_UPDATE_LEIDO", iD_NOTIFICACIONParameter, eSTADOParameter);
        }
    
        public virtual int SP_TB_PERMISO_DELETE_HARD(Nullable<int> iD_ROL, Nullable<int> iD_RECURSO)
        {
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(int));
    
            var iD_RECURSOParameter = iD_RECURSO.HasValue ?
                new ObjectParameter("ID_RECURSO", iD_RECURSO) :
                new ObjectParameter("ID_RECURSO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_PERMISO_DELETE_HARD", iD_ROLParameter, iD_RECURSOParameter);
        }
    
        public virtual int SP_TB_PERMISO_DELETE_SOFT(Nullable<int> iD_ROL, Nullable<int> iD_RECURSO, Nullable<int> uSUARIO_ACTUALIZA)
        {
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(int));
    
            var iD_RECURSOParameter = iD_RECURSO.HasValue ?
                new ObjectParameter("ID_RECURSO", iD_RECURSO) :
                new ObjectParameter("ID_RECURSO", typeof(int));
    
            var uSUARIO_ACTUALIZAParameter = uSUARIO_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ACTUALIZA", uSUARIO_ACTUALIZA) :
                new ObjectParameter("USUARIO_ACTUALIZA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_PERMISO_DELETE_SOFT", iD_ROLParameter, iD_RECURSOParameter, uSUARIO_ACTUALIZAParameter);
        }
    
        public virtual ObjectResult<SP_TB_PERMISO_GetAll_Result> SP_TB_PERMISO_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_PERMISO_GetAll_Result>("SP_TB_PERMISO_GetAll");
        }
    
        public virtual ObjectResult<SP_TB_PERMISO_GetAllWithDeleted_Result> SP_TB_PERMISO_GetAllWithDeleted()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_PERMISO_GetAllWithDeleted_Result>("SP_TB_PERMISO_GetAllWithDeleted");
        }
    
        public virtual ObjectResult<SP_TB_PERMISO_GetByRecurso_Result> SP_TB_PERMISO_GetByRecurso(Nullable<int> iD_RECURSO)
        {
            var iD_RECURSOParameter = iD_RECURSO.HasValue ?
                new ObjectParameter("ID_RECURSO", iD_RECURSO) :
                new ObjectParameter("ID_RECURSO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_PERMISO_GetByRecurso_Result>("SP_TB_PERMISO_GetByRecurso", iD_RECURSOParameter);
        }
    
        public virtual ObjectResult<SP_TB_PERMISO_GetByRol_Result> SP_TB_PERMISO_GetByRol(Nullable<int> iD_ROL)
        {
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_PERMISO_GetByRol_Result>("SP_TB_PERMISO_GetByRol", iD_ROLParameter);
        }
    
        public virtual ObjectResult<SP_TB_PERMISO_GetByRolRecurso_Result> SP_TB_PERMISO_GetByRolRecurso(Nullable<int> iD_RECURSO)
        {
            var iD_RECURSOParameter = iD_RECURSO.HasValue ?
                new ObjectParameter("ID_RECURSO", iD_RECURSO) :
                new ObjectParameter("ID_RECURSO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_PERMISO_GetByRolRecurso_Result>("SP_TB_PERMISO_GetByRolRecurso", iD_RECURSOParameter);
        }
    
        public virtual ObjectResult<SP_TB_PERMISO_GetDeleted_Result> SP_TB_PERMISO_GetDeleted()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_PERMISO_GetDeleted_Result>("SP_TB_PERMISO_GetDeleted");
        }
    
        public virtual int SP_TB_PERMISO_INSERT(Nullable<int> iD_ROL, Nullable<int> iD_RECURSO, Nullable<int> uSUARIO_CREA)
        {
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(int));
    
            var iD_RECURSOParameter = iD_RECURSO.HasValue ?
                new ObjectParameter("ID_RECURSO", iD_RECURSO) :
                new ObjectParameter("ID_RECURSO", typeof(int));
    
            var uSUARIO_CREAParameter = uSUARIO_CREA.HasValue ?
                new ObjectParameter("USUARIO_CREA", uSUARIO_CREA) :
                new ObjectParameter("USUARIO_CREA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_PERMISO_INSERT", iD_ROLParameter, iD_RECURSOParameter, uSUARIO_CREAParameter);
        }
    
        public virtual int SP_TB_PERMISO_RestoreById(Nullable<int> iD_ROL, Nullable<int> iD_RECURSO, Nullable<int> uSUARIO_ACTUALIZA)
        {
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(int));
    
            var iD_RECURSOParameter = iD_RECURSO.HasValue ?
                new ObjectParameter("ID_RECURSO", iD_RECURSO) :
                new ObjectParameter("ID_RECURSO", typeof(int));
    
            var uSUARIO_ACTUALIZAParameter = uSUARIO_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ACTUALIZA", uSUARIO_ACTUALIZA) :
                new ObjectParameter("USUARIO_ACTUALIZA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_PERMISO_RestoreById", iD_ROLParameter, iD_RECURSOParameter, uSUARIO_ACTUALIZAParameter);
        }
    
        public virtual int SP_TB_PERSONA_DELETE_HARD(Nullable<int> iD_PERSONA)
        {
            var iD_PERSONAParameter = iD_PERSONA.HasValue ?
                new ObjectParameter("ID_PERSONA", iD_PERSONA) :
                new ObjectParameter("ID_PERSONA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_PERSONA_DELETE_HARD", iD_PERSONAParameter);
        }
    
        public virtual int SP_TB_PERSONA_DELETE_SOFT(Nullable<int> iD_PERSONA, Nullable<int> uSUARIO_ACTUALIZA)
        {
            var iD_PERSONAParameter = iD_PERSONA.HasValue ?
                new ObjectParameter("ID_PERSONA", iD_PERSONA) :
                new ObjectParameter("ID_PERSONA", typeof(int));
    
            var uSUARIO_ACTUALIZAParameter = uSUARIO_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ACTUALIZA", uSUARIO_ACTUALIZA) :
                new ObjectParameter("USUARIO_ACTUALIZA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_PERSONA_DELETE_SOFT", iD_PERSONAParameter, uSUARIO_ACTUALIZAParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TB_PERSONA_EsCorreoUnico(string cORREO_E)
        {
            var cORREO_EParameter = cORREO_E != null ?
                new ObjectParameter("CORREO_E", cORREO_E) :
                new ObjectParameter("CORREO_E", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TB_PERSONA_EsCorreoUnico", cORREO_EParameter);
        }
    
        public virtual ObjectResult<SP_TB_PERSONA_GetAll_Result> SP_TB_PERSONA_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_PERSONA_GetAll_Result>("SP_TB_PERSONA_GetAll");
        }
    
        public virtual ObjectResult<SP_TB_PERSONA_GetAllWithDeleted_Result> SP_TB_PERSONA_GetAllWithDeleted()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_PERSONA_GetAllWithDeleted_Result>("SP_TB_PERSONA_GetAllWithDeleted");
        }
    
        public virtual ObjectResult<SP_TB_PERSONA_GetByCorreoE_Result> SP_TB_PERSONA_GetByCorreoE(string cORREO_E)
        {
            var cORREO_EParameter = cORREO_E != null ?
                new ObjectParameter("CORREO_E", cORREO_E) :
                new ObjectParameter("CORREO_E", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_PERSONA_GetByCorreoE_Result>("SP_TB_PERSONA_GetByCorreoE", cORREO_EParameter);
        }
    
        public virtual ObjectResult<SP_TB_PERSONA_GetByIdPersona_Result> SP_TB_PERSONA_GetByIdPersona(Nullable<int> iD_PERSONA)
        {
            var iD_PERSONAParameter = iD_PERSONA.HasValue ?
                new ObjectParameter("ID_PERSONA", iD_PERSONA) :
                new ObjectParameter("ID_PERSONA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_PERSONA_GetByIdPersona_Result>("SP_TB_PERSONA_GetByIdPersona", iD_PERSONAParameter);
        }
    
        public virtual ObjectResult<SP_TB_PERSONA_GetDeleted_Result> SP_TB_PERSONA_GetDeleted()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_PERSONA_GetDeleted_Result>("SP_TB_PERSONA_GetDeleted");
        }
    
        public virtual int SP_TB_PERSONA_InsertPersona(string nOMBRES, string aPELLIDOS, string cORREO_E, string tEL_FIJO, string tEL_CEL, Nullable<int> iD_MUNICIPIO, string dIRECCION, Nullable<int> uSUARIO_CREA)
        {
            var nOMBRESParameter = nOMBRES != null ?
                new ObjectParameter("NOMBRES", nOMBRES) :
                new ObjectParameter("NOMBRES", typeof(string));
    
            var aPELLIDOSParameter = aPELLIDOS != null ?
                new ObjectParameter("APELLIDOS", aPELLIDOS) :
                new ObjectParameter("APELLIDOS", typeof(string));
    
            var cORREO_EParameter = cORREO_E != null ?
                new ObjectParameter("CORREO_E", cORREO_E) :
                new ObjectParameter("CORREO_E", typeof(string));
    
            var tEL_FIJOParameter = tEL_FIJO != null ?
                new ObjectParameter("TEL_FIJO", tEL_FIJO) :
                new ObjectParameter("TEL_FIJO", typeof(string));
    
            var tEL_CELParameter = tEL_CEL != null ?
                new ObjectParameter("TEL_CEL", tEL_CEL) :
                new ObjectParameter("TEL_CEL", typeof(string));
    
            var iD_MUNICIPIOParameter = iD_MUNICIPIO.HasValue ?
                new ObjectParameter("ID_MUNICIPIO", iD_MUNICIPIO) :
                new ObjectParameter("ID_MUNICIPIO", typeof(int));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var uSUARIO_CREAParameter = uSUARIO_CREA.HasValue ?
                new ObjectParameter("USUARIO_CREA", uSUARIO_CREA) :
                new ObjectParameter("USUARIO_CREA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_PERSONA_InsertPersona", nOMBRESParameter, aPELLIDOSParameter, cORREO_EParameter, tEL_FIJOParameter, tEL_CELParameter, iD_MUNICIPIOParameter, dIRECCIONParameter, uSUARIO_CREAParameter);
        }
    
        public virtual int SP_TB_PERSONA_RestoreById(Nullable<int> iD_PERSONA, Nullable<int> uSUARIO_ACTUALIZA)
        {
            var iD_PERSONAParameter = iD_PERSONA.HasValue ?
                new ObjectParameter("ID_PERSONA", iD_PERSONA) :
                new ObjectParameter("ID_PERSONA", typeof(int));
    
            var uSUARIO_ACTUALIZAParameter = uSUARIO_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ACTUALIZA", uSUARIO_ACTUALIZA) :
                new ObjectParameter("USUARIO_ACTUALIZA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_PERSONA_RestoreById", iD_PERSONAParameter, uSUARIO_ACTUALIZAParameter);
        }
    
        public virtual int SP_TB_PERSONA_UPDATE(Nullable<int> iD_PERSONA, Nullable<int> iD_MUNICIPIO, string nOMBRES, string tEL_FIJO, string tEL_CEL, string aPELLIDOS, string cORREO_E, Nullable<int> uSUARIO_ACTUALIZA)
        {
            var iD_PERSONAParameter = iD_PERSONA.HasValue ?
                new ObjectParameter("ID_PERSONA", iD_PERSONA) :
                new ObjectParameter("ID_PERSONA", typeof(int));
    
            var iD_MUNICIPIOParameter = iD_MUNICIPIO.HasValue ?
                new ObjectParameter("ID_MUNICIPIO", iD_MUNICIPIO) :
                new ObjectParameter("ID_MUNICIPIO", typeof(int));
    
            var nOMBRESParameter = nOMBRES != null ?
                new ObjectParameter("NOMBRES", nOMBRES) :
                new ObjectParameter("NOMBRES", typeof(string));
    
            var tEL_FIJOParameter = tEL_FIJO != null ?
                new ObjectParameter("TEL_FIJO", tEL_FIJO) :
                new ObjectParameter("TEL_FIJO", typeof(string));
    
            var tEL_CELParameter = tEL_CEL != null ?
                new ObjectParameter("TEL_CEL", tEL_CEL) :
                new ObjectParameter("TEL_CEL", typeof(string));
    
            var aPELLIDOSParameter = aPELLIDOS != null ?
                new ObjectParameter("APELLIDOS", aPELLIDOS) :
                new ObjectParameter("APELLIDOS", typeof(string));
    
            var cORREO_EParameter = cORREO_E != null ?
                new ObjectParameter("CORREO_E", cORREO_E) :
                new ObjectParameter("CORREO_E", typeof(string));
    
            var uSUARIO_ACTUALIZAParameter = uSUARIO_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ACTUALIZA", uSUARIO_ACTUALIZA) :
                new ObjectParameter("USUARIO_ACTUALIZA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_PERSONA_UPDATE", iD_PERSONAParameter, iD_MUNICIPIOParameter, nOMBRESParameter, tEL_FIJOParameter, tEL_CELParameter, aPELLIDOSParameter, cORREO_EParameter, uSUARIO_ACTUALIZAParameter);
        }
    
        public virtual ObjectResult<SP_TB_PROBLEMA_ConsultarProblema_Result> SP_TB_PROBLEMA_ConsultarProblema(Nullable<int> idProblema)
        {
            var idProblemaParameter = idProblema.HasValue ?
                new ObjectParameter("IdProblema", idProblema) :
                new ObjectParameter("IdProblema", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_PROBLEMA_ConsultarProblema_Result>("SP_TB_PROBLEMA_ConsultarProblema", idProblemaParameter);
        }
    
        public virtual int SP_TB_PROBLEMA_InsertProblema(Nullable<int> idBeneficiario, Nullable<int> idEstadoProceso, string mercado, Nullable<int> cantEmpleados, Nullable<bool> requiereApoyo, string nombreProblema, string descripcionNegocio, string ventaDia, Nullable<decimal> ventaMes, string descripcionProblema, string descripcionOtroProblema)
        {
            var idBeneficiarioParameter = idBeneficiario.HasValue ?
                new ObjectParameter("IdBeneficiario", idBeneficiario) :
                new ObjectParameter("IdBeneficiario", typeof(int));
    
            var idEstadoProcesoParameter = idEstadoProceso.HasValue ?
                new ObjectParameter("IdEstadoProceso", idEstadoProceso) :
                new ObjectParameter("IdEstadoProceso", typeof(int));
    
            var mercadoParameter = mercado != null ?
                new ObjectParameter("Mercado", mercado) :
                new ObjectParameter("Mercado", typeof(string));
    
            var cantEmpleadosParameter = cantEmpleados.HasValue ?
                new ObjectParameter("CantEmpleados", cantEmpleados) :
                new ObjectParameter("CantEmpleados", typeof(int));
    
            var requiereApoyoParameter = requiereApoyo.HasValue ?
                new ObjectParameter("RequiereApoyo", requiereApoyo) :
                new ObjectParameter("RequiereApoyo", typeof(bool));
    
            var nombreProblemaParameter = nombreProblema != null ?
                new ObjectParameter("NombreProblema", nombreProblema) :
                new ObjectParameter("NombreProblema", typeof(string));
    
            var descripcionNegocioParameter = descripcionNegocio != null ?
                new ObjectParameter("DescripcionNegocio", descripcionNegocio) :
                new ObjectParameter("DescripcionNegocio", typeof(string));
    
            var ventaDiaParameter = ventaDia != null ?
                new ObjectParameter("VentaDia", ventaDia) :
                new ObjectParameter("VentaDia", typeof(string));
    
            var ventaMesParameter = ventaMes.HasValue ?
                new ObjectParameter("VentaMes", ventaMes) :
                new ObjectParameter("VentaMes", typeof(decimal));
    
            var descripcionProblemaParameter = descripcionProblema != null ?
                new ObjectParameter("DescripcionProblema", descripcionProblema) :
                new ObjectParameter("DescripcionProblema", typeof(string));
    
            var descripcionOtroProblemaParameter = descripcionOtroProblema != null ?
                new ObjectParameter("DescripcionOtroProblema", descripcionOtroProblema) :
                new ObjectParameter("DescripcionOtroProblema", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_PROBLEMA_InsertProblema", idBeneficiarioParameter, idEstadoProcesoParameter, mercadoParameter, cantEmpleadosParameter, requiereApoyoParameter, nombreProblemaParameter, descripcionNegocioParameter, ventaDiaParameter, ventaMesParameter, descripcionProblemaParameter, descripcionOtroProblemaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TB_PROBLEMA_TieneBeneficiarioAsociado(Nullable<int> idBeneficiario)
        {
            var idBeneficiarioParameter = idBeneficiario.HasValue ?
                new ObjectParameter("IdBeneficiario", idBeneficiario) :
                new ObjectParameter("IdBeneficiario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TB_PROBLEMA_TieneBeneficiarioAsociado", idBeneficiarioParameter);
        }
    
        public virtual int SP_TB_RECURSO_DELETE_HARD(Nullable<int> iD_RECURSO)
        {
            var iD_RECURSOParameter = iD_RECURSO.HasValue ?
                new ObjectParameter("ID_RECURSO", iD_RECURSO) :
                new ObjectParameter("ID_RECURSO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_RECURSO_DELETE_HARD", iD_RECURSOParameter);
        }
    
        public virtual int SP_TB_RECURSO_DELETE_SOFT(Nullable<int> iD_RECURSO, Nullable<int> uSUARIO_ACTUALIZA)
        {
            var iD_RECURSOParameter = iD_RECURSO.HasValue ?
                new ObjectParameter("ID_RECURSO", iD_RECURSO) :
                new ObjectParameter("ID_RECURSO", typeof(int));
    
            var uSUARIO_ACTUALIZAParameter = uSUARIO_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ACTUALIZA", uSUARIO_ACTUALIZA) :
                new ObjectParameter("USUARIO_ACTUALIZA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_RECURSO_DELETE_SOFT", iD_RECURSOParameter, uSUARIO_ACTUALIZAParameter);
        }
    
        public virtual ObjectResult<SP_TB_RECURSO_GetAll_Result> SP_TB_RECURSO_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_RECURSO_GetAll_Result>("SP_TB_RECURSO_GetAll");
        }
    
        public virtual ObjectResult<SP_TB_RECURSO_GetAllWithDeleted_Result> SP_TB_RECURSO_GetAllWithDeleted()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_RECURSO_GetAllWithDeleted_Result>("SP_TB_RECURSO_GetAllWithDeleted");
        }
    
        public virtual ObjectResult<SP_TB_RECURSO_GetById_Result> SP_TB_RECURSO_GetById(Nullable<int> iD_RECURSO)
        {
            var iD_RECURSOParameter = iD_RECURSO.HasValue ?
                new ObjectParameter("ID_RECURSO", iD_RECURSO) :
                new ObjectParameter("ID_RECURSO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_RECURSO_GetById_Result>("SP_TB_RECURSO_GetById", iD_RECURSOParameter);
        }
    
        public virtual ObjectResult<SP_TB_RECURSO_GetByUrlRecurso_Result> SP_TB_RECURSO_GetByUrlRecurso(string uRL_RECURSO)
        {
            var uRL_RECURSOParameter = uRL_RECURSO != null ?
                new ObjectParameter("URL_RECURSO", uRL_RECURSO) :
                new ObjectParameter("URL_RECURSO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_RECURSO_GetByUrlRecurso_Result>("SP_TB_RECURSO_GetByUrlRecurso", uRL_RECURSOParameter);
        }
    
        public virtual ObjectResult<SP_TB_RECURSO_GetDeleted_Result> SP_TB_RECURSO_GetDeleted()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_RECURSO_GetDeleted_Result>("SP_TB_RECURSO_GetDeleted");
        }
    
        public virtual int SP_TB_RECURSO_INSERT(string uRL_RECURSO, string nOMBRE, Nullable<int> uSUARIO_CREA)
        {
            var uRL_RECURSOParameter = uRL_RECURSO != null ?
                new ObjectParameter("URL_RECURSO", uRL_RECURSO) :
                new ObjectParameter("URL_RECURSO", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var uSUARIO_CREAParameter = uSUARIO_CREA.HasValue ?
                new ObjectParameter("USUARIO_CREA", uSUARIO_CREA) :
                new ObjectParameter("USUARIO_CREA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_RECURSO_INSERT", uRL_RECURSOParameter, nOMBREParameter, uSUARIO_CREAParameter);
        }
    
        public virtual int SP_TB_RECURSO_RestoreById(Nullable<int> iD_RECURSO, Nullable<int> uSUARIO_ACTUALIZA)
        {
            var iD_RECURSOParameter = iD_RECURSO.HasValue ?
                new ObjectParameter("ID_RECURSO", iD_RECURSO) :
                new ObjectParameter("ID_RECURSO", typeof(int));
    
            var uSUARIO_ACTUALIZAParameter = uSUARIO_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ACTUALIZA", uSUARIO_ACTUALIZA) :
                new ObjectParameter("USUARIO_ACTUALIZA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_RECURSO_RestoreById", iD_RECURSOParameter, uSUARIO_ACTUALIZAParameter);
        }
    
        public virtual int SP_TB_RECURSO_UPDATE(Nullable<int> iD_RECURSO, string uRL_RECURSO, string nOMBRE, Nullable<int> uSUARIO_ACTUALIZA)
        {
            var iD_RECURSOParameter = iD_RECURSO.HasValue ?
                new ObjectParameter("ID_RECURSO", iD_RECURSO) :
                new ObjectParameter("ID_RECURSO", typeof(int));
    
            var uRL_RECURSOParameter = uRL_RECURSO != null ?
                new ObjectParameter("URL_RECURSO", uRL_RECURSO) :
                new ObjectParameter("URL_RECURSO", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var uSUARIO_ACTUALIZAParameter = uSUARIO_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ACTUALIZA", uSUARIO_ACTUALIZA) :
                new ObjectParameter("USUARIO_ACTUALIZA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_RECURSO_UPDATE", iD_RECURSOParameter, uRL_RECURSOParameter, nOMBREParameter, uSUARIO_ACTUALIZAParameter);
        }
    
        public virtual int SP_TB_ROL_DELETE_HARD(Nullable<int> iD_ROL)
        {
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_ROL_DELETE_HARD", iD_ROLParameter);
        }
    
        public virtual int SP_TB_ROL_DELETE_SOFT(Nullable<int> iD_ROL, Nullable<int> uSUARIO_ACTUALIZA)
        {
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(int));
    
            var uSUARIO_ACTUALIZAParameter = uSUARIO_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ACTUALIZA", uSUARIO_ACTUALIZA) :
                new ObjectParameter("USUARIO_ACTUALIZA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_ROL_DELETE_SOFT", iD_ROLParameter, uSUARIO_ACTUALIZAParameter);
        }
    
        public virtual ObjectResult<SP_TB_ROL_GetAll_Result> SP_TB_ROL_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_ROL_GetAll_Result>("SP_TB_ROL_GetAll");
        }
    
        public virtual ObjectResult<SP_TB_ROL_GetAllWithDeleted_Result> SP_TB_ROL_GetAllWithDeleted()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_ROL_GetAllWithDeleted_Result>("SP_TB_ROL_GetAllWithDeleted");
        }
    
        public virtual ObjectResult<SP_TB_ROL_GetByIdRol_Result> SP_TB_ROL_GetByIdRol(Nullable<int> iD_ROL)
        {
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_ROL_GetByIdRol_Result>("SP_TB_ROL_GetByIdRol", iD_ROLParameter);
        }
    
        public virtual ObjectResult<SP_TB_ROL_GetByNombre_Result> SP_TB_ROL_GetByNombre(string nOMBRE)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_ROL_GetByNombre_Result>("SP_TB_ROL_GetByNombre", nOMBREParameter);
        }
    
        public virtual ObjectResult<SP_TB_ROL_GetDeleted_Result> SP_TB_ROL_GetDeleted()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_ROL_GetDeleted_Result>("SP_TB_ROL_GetDeleted");
        }
    
        public virtual int SP_TB_ROL_INSERT(string nOMBRE, string dESCRIPCION, Nullable<int> uSUARIO_CREA)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var uSUARIO_CREAParameter = uSUARIO_CREA.HasValue ?
                new ObjectParameter("USUARIO_CREA", uSUARIO_CREA) :
                new ObjectParameter("USUARIO_CREA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_ROL_INSERT", nOMBREParameter, dESCRIPCIONParameter, uSUARIO_CREAParameter);
        }
    
        public virtual int SP_TB_ROL_RestoreById(Nullable<int> iD_ROL, Nullable<int> uSUARIO_ACTUALIZA)
        {
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(int));
    
            var uSUARIO_ACTUALIZAParameter = uSUARIO_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ACTUALIZA", uSUARIO_ACTUALIZA) :
                new ObjectParameter("USUARIO_ACTUALIZA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_ROL_RestoreById", iD_ROLParameter, uSUARIO_ACTUALIZAParameter);
        }
    
        public virtual int SP_TB_ROL_UPDATE(Nullable<int> iD_ROL, string nOMBRE, string dESCRIPCION, Nullable<int> uSUARIO_ACTUALIZA)
        {
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var uSUARIO_ACTUALIZAParameter = uSUARIO_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ACTUALIZA", uSUARIO_ACTUALIZA) :
                new ObjectParameter("USUARIO_ACTUALIZA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_ROL_UPDATE", iD_ROLParameter, nOMBREParameter, dESCRIPCIONParameter, uSUARIO_ACTUALIZAParameter);
        }
    
        public virtual int SP_TB_USUARIO_DELETE_HARD(Nullable<int> iD_USUARIO)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_USUARIO_DELETE_HARD", iD_USUARIOParameter);
        }
    
        public virtual int SP_TB_USUARIO_DELETE_SOFT(Nullable<int> iD_USUARIO, Nullable<int> uSUARIO_ACTUALIZA)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            var uSUARIO_ACTUALIZAParameter = uSUARIO_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ACTUALIZA", uSUARIO_ACTUALIZA) :
                new ObjectParameter("USUARIO_ACTUALIZA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_USUARIO_DELETE_SOFT", iD_USUARIOParameter, uSUARIO_ACTUALIZAParameter);
        }
    
        public virtual ObjectResult<SP_TB_USUARIO_GetAll_Result> SP_TB_USUARIO_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_USUARIO_GetAll_Result>("SP_TB_USUARIO_GetAll");
        }
    
        public virtual ObjectResult<SP_TB_USUARIO_GetAllWithDeleted_Result> SP_TB_USUARIO_GetAllWithDeleted()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_USUARIO_GetAllWithDeleted_Result>("SP_TB_USUARIO_GetAllWithDeleted");
        }
    
        public virtual ObjectResult<SP_TB_USUARIO_GetByIdPersona_Result> SP_TB_USUARIO_GetByIdPersona(Nullable<int> iD_PERSONA)
        {
            var iD_PERSONAParameter = iD_PERSONA.HasValue ?
                new ObjectParameter("ID_PERSONA", iD_PERSONA) :
                new ObjectParameter("ID_PERSONA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_USUARIO_GetByIdPersona_Result>("SP_TB_USUARIO_GetByIdPersona", iD_PERSONAParameter);
        }
    
        public virtual ObjectResult<SP_TB_USUARIO_GetByIdUsuario_Result> SP_TB_USUARIO_GetByIdUsuario(Nullable<int> iD_USUARIO)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_USUARIO_GetByIdUsuario_Result>("SP_TB_USUARIO_GetByIdUsuario", iD_USUARIOParameter);
        }
    
        public virtual ObjectResult<SP_TB_USUARIO_GetDeleted_Result> SP_TB_USUARIO_GetDeleted()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TB_USUARIO_GetDeleted_Result>("SP_TB_USUARIO_GetDeleted");
        }
    
        public virtual ObjectResult<string> SP_TB_USUARIO_GetIdSesion(Nullable<int> iD_USUARIO)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_TB_USUARIO_GetIdSesion", iD_USUARIOParameter);
        }
    
        public virtual int SP_TB_USUARIO_INSERT(Nullable<int> iD_ROL, Nullable<int> iD_PERSONA, string nOMBRE_USUARIO, string cONTRASENA, Nullable<int> uSUARIO_CREA)
        {
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(int));
    
            var iD_PERSONAParameter = iD_PERSONA.HasValue ?
                new ObjectParameter("ID_PERSONA", iD_PERSONA) :
                new ObjectParameter("ID_PERSONA", typeof(int));
    
            var nOMBRE_USUARIOParameter = nOMBRE_USUARIO != null ?
                new ObjectParameter("NOMBRE_USUARIO", nOMBRE_USUARIO) :
                new ObjectParameter("NOMBRE_USUARIO", typeof(string));
    
            var cONTRASENAParameter = cONTRASENA != null ?
                new ObjectParameter("CONTRASENA", cONTRASENA) :
                new ObjectParameter("CONTRASENA", typeof(string));
    
            var uSUARIO_CREAParameter = uSUARIO_CREA.HasValue ?
                new ObjectParameter("USUARIO_CREA", uSUARIO_CREA) :
                new ObjectParameter("USUARIO_CREA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_USUARIO_INSERT", iD_ROLParameter, iD_PERSONAParameter, nOMBRE_USUARIOParameter, cONTRASENAParameter, uSUARIO_CREAParameter);
        }
    
        public virtual int SP_TB_USUARIO_RestoreById(Nullable<int> iD_USUARIO, Nullable<int> uSUARIO_ACTUALIZA)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            var uSUARIO_ACTUALIZAParameter = uSUARIO_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ACTUALIZA", uSUARIO_ACTUALIZA) :
                new ObjectParameter("USUARIO_ACTUALIZA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_USUARIO_RestoreById", iD_USUARIOParameter, uSUARIO_ACTUALIZAParameter);
        }
    
        public virtual int SP_TB_USUARIO_UPDATE(Nullable<int> iD_USUARIO, Nullable<int> iD_ROL, Nullable<int> iD_PERSONA, string nOMBRE_USUARIO, string cONTRASENA, Nullable<int> uSUARIO_ACTUALIZA)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(int));
    
            var iD_PERSONAParameter = iD_PERSONA.HasValue ?
                new ObjectParameter("ID_PERSONA", iD_PERSONA) :
                new ObjectParameter("ID_PERSONA", typeof(int));
    
            var nOMBRE_USUARIOParameter = nOMBRE_USUARIO != null ?
                new ObjectParameter("NOMBRE_USUARIO", nOMBRE_USUARIO) :
                new ObjectParameter("NOMBRE_USUARIO", typeof(string));
    
            var cONTRASENAParameter = cONTRASENA != null ?
                new ObjectParameter("CONTRASENA", cONTRASENA) :
                new ObjectParameter("CONTRASENA", typeof(string));
    
            var uSUARIO_ACTUALIZAParameter = uSUARIO_ACTUALIZA.HasValue ?
                new ObjectParameter("USUARIO_ACTUALIZA", uSUARIO_ACTUALIZA) :
                new ObjectParameter("USUARIO_ACTUALIZA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_USUARIO_UPDATE", iD_USUARIOParameter, iD_ROLParameter, iD_PERSONAParameter, nOMBRE_USUARIOParameter, cONTRASENAParameter, uSUARIO_ACTUALIZAParameter);
        }
    
        public virtual int SP_TB_USUARIO_UPDATE_AUTENTICADO(Nullable<int> iD_USUARIO, string iD_SESION, Nullable<short> eSTADO)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            var iD_SESIONParameter = iD_SESION != null ?
                new ObjectParameter("ID_SESION", iD_SESION) :
                new ObjectParameter("ID_SESION", typeof(string));
    
            var eSTADOParameter = eSTADO.HasValue ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_USUARIO_UPDATE_AUTENTICADO", iD_USUARIOParameter, iD_SESIONParameter, eSTADOParameter);
        }
    
        public virtual ObjectResult<SP_TBC_DEPARTAMENTO_GetDepartamentos_Result> SP_TBC_DEPARTAMENTO_GetDepartamentos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TBC_DEPARTAMENTO_GetDepartamentos_Result>("SP_TBC_DEPARTAMENTO_GetDepartamentos");
        }
    
        public virtual ObjectResult<SP_TBC_ESTADO_PROCESO_GetAll_Result> SP_TBC_ESTADO_PROCESO_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TBC_ESTADO_PROCESO_GetAll_Result>("SP_TBC_ESTADO_PROCESO_GetAll");
        }
    
        public virtual ObjectResult<SP_TBC_ESTADO_PROCESO_GetByIdEstadoProceso_Result> SP_TBC_ESTADO_PROCESO_GetByIdEstadoProceso(Nullable<int> iD_ESTADO_PROCESO)
        {
            var iD_ESTADO_PROCESOParameter = iD_ESTADO_PROCESO.HasValue ?
                new ObjectParameter("ID_ESTADO_PROCESO", iD_ESTADO_PROCESO) :
                new ObjectParameter("ID_ESTADO_PROCESO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TBC_ESTADO_PROCESO_GetByIdEstadoProceso_Result>("SP_TBC_ESTADO_PROCESO_GetByIdEstadoProceso", iD_ESTADO_PROCESOParameter);
        }
    
        public virtual ObjectResult<SP_TBC_ESTADO_PROCESO_GetByIdProceso_Result> SP_TBC_ESTADO_PROCESO_GetByIdProceso(Nullable<int> iD_PROCESO)
        {
            var iD_PROCESOParameter = iD_PROCESO.HasValue ?
                new ObjectParameter("ID_PROCESO", iD_PROCESO) :
                new ObjectParameter("ID_PROCESO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TBC_ESTADO_PROCESO_GetByIdProceso_Result>("SP_TBC_ESTADO_PROCESO_GetByIdProceso", iD_PROCESOParameter);
        }
    
        public virtual ObjectResult<SP_TBC_MUNICIPIO_GetDepartamentoByIdMunicipio_Result> SP_TBC_MUNICIPIO_GetDepartamentoByIdMunicipio(Nullable<int> iD_MUNICIPIO)
        {
            var iD_MUNICIPIOParameter = iD_MUNICIPIO.HasValue ?
                new ObjectParameter("ID_MUNICIPIO", iD_MUNICIPIO) :
                new ObjectParameter("ID_MUNICIPIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TBC_MUNICIPIO_GetDepartamentoByIdMunicipio_Result>("SP_TBC_MUNICIPIO_GetDepartamentoByIdMunicipio", iD_MUNICIPIOParameter);
        }
    
        public virtual ObjectResult<SP_TBC_MUNICIPIO_GetMunicipiosXDepartamento_Result> SP_TBC_MUNICIPIO_GetMunicipiosXDepartamento(Nullable<int> departamentoId)
        {
            var departamentoIdParameter = departamentoId.HasValue ?
                new ObjectParameter("DepartamentoId", departamentoId) :
                new ObjectParameter("DepartamentoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TBC_MUNICIPIO_GetMunicipiosXDepartamento_Result>("SP_TBC_MUNICIPIO_GetMunicipiosXDepartamento", departamentoIdParameter);
        }
    
        public virtual ObjectResult<SP_TBC_SECTOR_ECONOMICO_GetSectores_Result> SP_TBC_SECTOR_ECONOMICO_GetSectores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TBC_SECTOR_ECONOMICO_GetSectores_Result>("SP_TBC_SECTOR_ECONOMICO_GetSectores");
        }
    
        public virtual ObjectResult<SP_TBC_TIPO_NOTIFICACION_GetByIdTipoNotificacion_Result> SP_TBC_TIPO_NOTIFICACION_GetByIdTipoNotificacion(Nullable<int> iD_TIPO_NOTIFICACION)
        {
            var iD_TIPO_NOTIFICACIONParameter = iD_TIPO_NOTIFICACION.HasValue ?
                new ObjectParameter("ID_TIPO_NOTIFICACION", iD_TIPO_NOTIFICACION) :
                new ObjectParameter("ID_TIPO_NOTIFICACION", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TBC_TIPO_NOTIFICACION_GetByIdTipoNotificacion_Result>("SP_TBC_TIPO_NOTIFICACION_GetByIdTipoNotificacion", iD_TIPO_NOTIFICACIONParameter);
        }
    
        public virtual int SP_TBC_TIPO_NOTIFICACION_INSERT(string cOLOR, string iCONO, string tITULO)
        {
            var cOLORParameter = cOLOR != null ?
                new ObjectParameter("COLOR", cOLOR) :
                new ObjectParameter("COLOR", typeof(string));
    
            var iCONOParameter = iCONO != null ?
                new ObjectParameter("ICONO", iCONO) :
                new ObjectParameter("ICONO", typeof(string));
    
            var tITULOParameter = tITULO != null ?
                new ObjectParameter("TITULO", tITULO) :
                new ObjectParameter("TITULO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TBC_TIPO_NOTIFICACION_INSERT", cOLORParameter, iCONOParameter, tITULOParameter);
        }
    
        public virtual int SP_TBC_TIPO_NOTIFICACION_UPDATE(Nullable<int> iD_TIPO_NOTIFICACION, string cOLOR, string iCONO, string tITULO)
        {
            var iD_TIPO_NOTIFICACIONParameter = iD_TIPO_NOTIFICACION.HasValue ?
                new ObjectParameter("ID_TIPO_NOTIFICACION", iD_TIPO_NOTIFICACION) :
                new ObjectParameter("ID_TIPO_NOTIFICACION", typeof(int));
    
            var cOLORParameter = cOLOR != null ?
                new ObjectParameter("COLOR", cOLOR) :
                new ObjectParameter("COLOR", typeof(string));
    
            var iCONOParameter = iCONO != null ?
                new ObjectParameter("ICONO", iCONO) :
                new ObjectParameter("ICONO", typeof(string));
    
            var tITULOParameter = tITULO != null ?
                new ObjectParameter("TITULO", tITULO) :
                new ObjectParameter("TITULO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TBC_TIPO_NOTIFICACION_UPDATE", iD_TIPO_NOTIFICACIONParameter, cOLORParameter, iCONOParameter, tITULOParameter);
        }
    }
}
