//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ACTIVIDAD
    {
        public int ID_ACTIVIDAD { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<int> USUARIO_CREA { get; set; }
        public System.DateTime FECHA { get; set; }
        public System.DateTime HORA { get; set; }
        public string DIRECCION { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<System.DateTime> FECHA_CREA { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZA { get; set; }
        public Nullable<System.DateTime> FECHA_BORRADO { get; set; }
    
        public virtual TB_USUARIO TB_USUARIO { get; set; }
        public virtual TB_USUARIO TB_USUARIO1 { get; set; }
    }
}
