//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EJECUCION
    {
        public int ID_EJECUCION { get; set; }
        public int ID_PROYECTO_ACTIVIDAD { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual TB_PROYECTO_ACTIVIDAD TB_PROYECTO_ACTIVIDAD { get; set; }
    }
}
