//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROYECTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PROYECTO()
        {
            this.TB_PROYECTO_ACTIVIDAD = new HashSet<TB_PROYECTO_ACTIVIDAD>();
            this.TB_SOLICITUD_SEGUIMIENTO = new HashSet<TB_SOLICITUD_SEGUIMIENTO>();
        }
    
        public int ID_PROYECTO { get; set; }
        public string COD_PROYECTO { get; set; }
        public int ID_PROBLEMA { get; set; }
        public int ID_TIPO_INICIATIVA { get; set; }
        public Nullable<int> USUARIO_CREA { get; set; }
        public Nullable<int> USUARIO_ACTUALIZA { get; set; }
        public Nullable<System.DateTime> FECHA_CREA { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZA { get; set; }
        public Nullable<System.DateTime> FECHA_BORRADO { get; set; }
    
        public virtual TB_PROBLEMA TB_PROBLEMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROYECTO_ACTIVIDAD> TB_PROYECTO_ACTIVIDAD { get; set; }
        public virtual TBC_TIPO_INICIATIVA TBC_TIPO_INICIATIVA { get; set; }
        public virtual TB_USUARIO TB_USUARIO { get; set; }
        public virtual TB_USUARIO TB_USUARIO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SOLICITUD_SEGUIMIENTO> TB_SOLICITUD_SEGUIMIENTO { get; set; }
    }
}
