//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROPUESTA
    {
        public int ID_PROPUESTA { get; set; }
        public int ID_PROBLEMA { get; set; }
        public int ID_USUARIO_FORMULA { get; set; }
        public Nullable<int> ID_ESTADO_PROCESO { get; set; }
        public Nullable<int> ID_TIPO_INICIATIVA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<System.DateTime> FECHA_CREA { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZA { get; set; }
        public Nullable<System.DateTime> FECHA_BORRADO { get; set; }
    
        public virtual TB_PROBLEMA TB_PROBLEMA { get; set; }
        public virtual TBC_ESTADO_PROCESO TBC_ESTADO_PROCESO { get; set; }
        public virtual TBC_TIPO_INICIATIVA TBC_TIPO_INICIATIVA { get; set; }
        public virtual TB_USUARIO TB_USUARIO { get; set; }
    }
}
