//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROYECTO_ACTIVIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PROYECTO_ACTIVIDAD()
        {
            this.TB_EJECUCION = new HashSet<TB_EJECUCION>();
        }
    
        public int ID_PROYECTO_ACTIVIDAD { get; set; }
        public int ID_ACTIVIDAD_INICIATIVA { get; set; }
        public int ID_PROYECTO { get; set; }
        public Nullable<int> USUARIO_CREA { get; set; }
        public Nullable<int> USUARIO_ACTUALIZA { get; set; }
        public short SEMANA_INICIO { get; set; }
        public short SEMANA_FIN { get; set; }
        public int PORCENTAJE_AVANCE { get; set; }
        public Nullable<System.DateTime> FECHA_CREA { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZA { get; set; }
        public Nullable<System.DateTime> FECHA_BORRADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_EJECUCION> TB_EJECUCION { get; set; }
        public virtual TB_PROYECTO TB_PROYECTO { get; set; }
        public virtual TBC_ACTIVIDAD_INICIATIVA TBC_ACTIVIDAD_INICIATIVA { get; set; }
        public virtual TB_USUARIO TB_USUARIO { get; set; }
        public virtual TB_USUARIO TB_USUARIO1 { get; set; }
    }
}
