//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PERMISO
    {
        public int ID_ROL { get; set; }
        public int ID_RECURSO { get; set; }
        public Nullable<int> USUARIO_CREA { get; set; }
        public Nullable<int> USUARIO_ACTUALIZA { get; set; }
        public Nullable<System.DateTime> FECHA_CREA { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZA { get; set; }
        public Nullable<System.DateTime> FECHA_BORRADO { get; set; }
    
        public virtual TB_RECURSO TB_RECURSO { get; set; }
        public virtual TB_USUARIO TB_USUARIO { get; set; }
        public virtual TB_USUARIO TB_USUARIO1 { get; set; }
        public virtual TB_ROL TB_ROL { get; set; }
    }
}
