//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROBLEMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PROBLEMA()
        {
            this.TB_PROPUESTA = new HashSet<TB_PROPUESTA>();
            this.TB_PROYECTO = new HashSet<TB_PROYECTO>();
        }
    
        public int ID_PROBLEMA { get; set; }
        public int ID_BENEFICIARIO { get; set; }
        public Nullable<int> ID_ESTADO_PROCESO { get; set; }
        public Nullable<int> USUARIO_ACTUALIZA { get; set; }
        public string MERCADO { get; set; }
        public int CANT_EMPLEADOS { get; set; }
        public bool REQUIERE_APOYO { get; set; }
        public string NOMBRE_PROBLEMA { get; set; }
        public string DESCRIPCION_NEGOCIO { get; set; }
        public string VENTA_DIA { get; set; }
        public Nullable<decimal> VENTA_MES { get; set; }
        public string DESCRIPCION_PROBLEMA { get; set; }
        public string DESCRIPCION_OTRO_PROBLEMA { get; set; }
        public Nullable<System.DateTime> FECHA_CREA { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZA { get; set; }
        public Nullable<System.DateTime> FECHA_BORRADO { get; set; }
    
        public virtual TB_BENEFICIARIO TB_BENEFICIARIO { get; set; }
        public virtual TBC_ESTADO_PROCESO TBC_ESTADO_PROCESO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROPUESTA> TB_PROPUESTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROYECTO> TB_PROYECTO { get; set; }
        public virtual TB_USUARIO TB_USUARIO { get; set; }
    }
}
