//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBC_ESTADO_PROCESO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBC_ESTADO_PROCESO()
        {
            this.TB_BENEFICIARIO = new HashSet<TB_BENEFICIARIO>();
            this.TB_PROBLEMA = new HashSet<TB_PROBLEMA>();
            this.TB_PROPUESTA = new HashSet<TB_PROPUESTA>();
        }
    
        public int ID_ESTADO_PROCESO { get; set; }
        public Nullable<int> ID_PROCESO { get; set; }
        public string CODIGO_ESTADO_PROCESO { get; set; }
        public string NOMBRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BENEFICIARIO> TB_BENEFICIARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROBLEMA> TB_PROBLEMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROPUESTA> TB_PROPUESTA { get; set; }
        public virtual TBC_PROCESO TBC_PROCESO { get; set; }
    }
}
