//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBC_TIPO_INICIATIVA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBC_TIPO_INICIATIVA()
        {
            this.TB_PROPUESTA = new HashSet<TB_PROPUESTA>();
            this.TB_PROYECTO = new HashSet<TB_PROYECTO>();
            this.TBC_ACTIVIDAD_INICIATIVA = new HashSet<TBC_ACTIVIDAD_INICIATIVA>();
        }
    
        public int ID_TIPO_INICIATIVA { get; set; }
        public string NOMBRE { get; set; }
        public string CODIGO_TIPO_INICIATVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROPUESTA> TB_PROPUESTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROYECTO> TB_PROYECTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBC_ACTIVIDAD_INICIATIVA> TBC_ACTIVIDAD_INICIATIVA { get; set; }
    }
}
