//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBC_SECTOR_ECONOMICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBC_SECTOR_ECONOMICO()
        {
            this.TB_BENEFICIARIO = new HashSet<TB_BENEFICIARIO>();
        }
    
        public int ID_SECTOR_ECONOMICO { get; set; }
        public string COD_SECTOR_ECONOMICO { get; set; }
        public string NOMBRE_SECTOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BENEFICIARIO> TB_BENEFICIARIO { get; set; }
    }
}
