//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBC_TIPO_NOTIFICACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBC_TIPO_NOTIFICACION()
        {
            this.TB_NOTIFICACION = new HashSet<TB_NOTIFICACION>();
        }
    
        public int ID_TIPO_NOTIFICACION { get; set; }
        public string COLOR { get; set; }
        public string ICONO { get; set; }
        public string TITULO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_NOTIFICACION> TB_NOTIFICACION { get; set; }
    }
}
